services:
  mariadb:
    container_name: db-mariadb
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootuser
      MARIADB_USER: user
      MARIADB_PASSWORD: user
    ports:
      - 3306:3306
    networks:
      - local_network
  phpmyadmin-maria:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-maria
    links:
      - mariadb
    environment:
      PMA_HOST: db-mariadb
      PMA_PORT: 3306
    restart: unless-stopped
    ports:
      - 8081:80
    networks:
      - local_network
    depends_on:
      - mariadb
networks:
  local_network:
